import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

/**
 * Font Configuration
 *
 * Using Next.js built-in Google Fonts integration:
 * - Geist (Sans) → assigned to CSS variable `--font-geist-sans`
 * - Geist Mono → assigned to CSS variable `--font-geist-mono`
 *
 * These variables are later applied to the <body> for consistent typography.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata for the application
 *
 * Used by Next.js to populate <head> with title and description.
 */
export const metadata = {
  title: "TV Shows",
  description: "Generated by create next app",
};

/**
 * RootLayout Component
 *
 * Provides the global layout structure for the Next.js app.
 * - Wraps all pages with <html> and <body>.
 * - Applies global font variables and antialiasing.
 * - Includes the Navbar at the top of every page.
 * - Renders child components passed via `children`.
 *
 * @component
 * @param {React.ReactNode} children - The page content to render inside the layout.
 * @example
 * // Usage in Next.js App Router
 * export default function Layout({ children }) {
 *   return (
 *     <RootLayout>
 *       <main>{children}</main>
 *     </RootLayout>
 *   );
 * }
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global navigation bar */}
        <Navbar />

        {/* Render page-specific content */}
        {children}
      </body>
    </html>
  );
}
